version: '3'

services:
  trust-service:
    image: nimbleplatform/trust-service:latest

  trust-db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: trustdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
    driver: local